// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlvb4YKEky_9oK1K3x8WS50TjZbY8hmmk',
    appId: '1:952224280189:web:5e4233d4bdb81889dd8b14',
    messagingSenderId: '952224280189',
    projectId: 'chat-app-82694',
    authDomain: 'chat-app-82694.firebaseapp.com',
    storageBucket: 'chat-app-82694.firebasestorage.app',
    measurementId: 'G-9YG68X63W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr11knV0L-heaK2r5Q9b61H5FmCFWh6S4',
    appId: '1:952224280189:android:a1239e3eb113c543dd8b14',
    messagingSenderId: '952224280189',
    projectId: 'chat-app-82694',
    storageBucket: 'chat-app-82694.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa5KsbeRPbAa2_3Rq_F0zKgQ61OF6mpW0',
    appId: '1:952224280189:ios:db3915d3883df7cfdd8b14',
    messagingSenderId: '952224280189',
    projectId: 'chat-app-82694',
    storageBucket: 'chat-app-82694.firebasestorage.app',
    iosBundleId: 'com.example.completeChatAppTharwat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa5KsbeRPbAa2_3Rq_F0zKgQ61OF6mpW0',
    appId: '1:952224280189:ios:db3915d3883df7cfdd8b14',
    messagingSenderId: '952224280189',
    projectId: 'chat-app-82694',
    storageBucket: 'chat-app-82694.firebasestorage.app',
    iosBundleId: 'com.example.completeChatAppTharwat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlvb4YKEky_9oK1K3x8WS50TjZbY8hmmk',
    appId: '1:952224280189:web:e717140e50c2b397dd8b14',
    messagingSenderId: '952224280189',
    projectId: 'chat-app-82694',
    authDomain: 'chat-app-82694.firebaseapp.com',
    storageBucket: 'chat-app-82694.firebasestorage.app',
    measurementId: 'G-90GQ1E4N5Y',
  );

}